### ISSUE TITLE
Notebooks don't work in binder

### ISSUE THREAD

**Issue by rabernat** [roxyboy/SouthernOcean-ARGO#1]
I just tried running the binder. I found that:
- The package imports don't work. e.g. in `COMCLIMphasing.ipynb`: `No module named 'cmocean'`
- The data are not available (it references file paths from Gyre)

These should either be fixed or else the binder links disabled. A broken binder is worse than no binder.

**Comment by roxyboy** [comment]
I should probably make the README more specific but Binder essentially only works for `SOCCOM/5904185.ipynb` in the repository.

**Comment by rabernat** [comment]
Great, then you can modify the binder link to open that notebook directly! 😄

**Comment by roxyboy** [comment]
PR #2 fixes this.
